name: Laravel

on:
  push:
    branches: [ Test ]
jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: | 
        cd Project 
        php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: |
       cd Project  
       composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Generate key
      run: |
        cd Project
        php artisan key:generate
    - name: Directory Permissions
      run: |
        cd Project
        chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        cd Project
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: |
        cd Project
        vendor/bin/phpunit
